//
// Created by misak on 17/03/2022.
//

#ifndef MAAKTNIETUIT_STANDAARD_NOTITIES_H
#define MAAKTNIETUIT_STANDAARD_NOTITIES_H

#define LENGTE 4
#define MAX_SPEED 16.6
#define MAX_VERSNELLING 1.44
#define MAX_REM 4.61
#define MIN_VOLG 4
#define SIM_TIJD 0.0166
#define VERTRAAG_AFSTAND 50
#define STOP_AFSTAND 15
#define VERTRAAG_FACTOR 0.4

#endif //MAAKTNIETUIT_STANDAARD_NOTITIES_H
